### ISSUE TITLE
Error with the Full Version of Julia 1.6 (Released on 26/03/2021)

### ISSUE THREAD

**Issue by RoyiAvital** [heetbeet/juliawin#45]
I downloaded the full version and got an error with `PyCall`:

![image](https://user-images.githubusercontent.com/7347975/112672814-04561400-8e75-11eb-9013-1670ba65608c.png)

It seems to have leftovers from you own computer.

By the way, it would be great to have a file with the version of JuliaWin in the folder (Both for the Julia used and the release ID of JuliaWin).

**Comment by heetbeet** [comment]
Thanks, I have removed the binaries from the release as to not let anyone else by accident install them. It seems like the PyCall pipeline got a bit more complex, so I have also added a bit more checks to the Juliawin portability script. I also added some logic to overwrite the conda QT config. I have also moved the portability logic to the bin directory for others to better see what steps are taken to try to keep Juliawin portable.

I'll make another release and add the binaries to it as soon as I find some time. In the mean while, the thin installer should work as normal.

**Comment by RoyiAvital** [comment]
Please also add someway to identify the JuliaWin version.

**Comment by heetbeet** [comment]
I moved the versioning issue over at https://github.com/heetbeet/juliawin/issues/48

**Comment by heetbeet** [comment]
As reference to this issue, here is the script that keeps portability in tact. I suspect this will grow in the future as more problems from different libraries pop up:
https://github.com/heetbeet/juliawin/blob/main/bin/activate-juliawin-portability.bat

The new releases are tagged as v1.6.0-1 and will include binaries

**Comment by RoyiAvital** [comment]
It seems the script watches if the location of the installation has changed and if so restarts the process, right?
Also the `qt.conf` I mentioned which needs update.
So it is like the idea I sent you over Slack how to solve it (Basically what I did manually to solve it).

I think a better process is to delete `PyCall`, `PyPlot` and `Conda` and redownload them.
Just like the script would do.

**Comment by heetbeet** [comment]
Yes, exactly. This script is added to the `activate-juliawin-environment.bat` script:
https://github.com/heetbeet/juliawin/blob/3cef97e4a95f15813a3c076562f4ed696630354c/bin/activate-juliawin-environment.bat#L26

And does the following:
- check whether the path has changed between runs, if so continue next bullet points
- overwrite `conda\qt.conf` with current paths
- delete `.julia\compiled`, `.julia\conda`, `.julia\\prefs\IJulia`
- do `Pkg.build` on `PyCall`, `Conda`, and `IJulia`

This doesn't require redownloading of anything and is automatically run at the beginning of every juliawin binary. The reason I don't want to delete and re-download the packages is that I want Juliawin to be portable and external-harddrive-friendly without requiring internet access.

**Comment by RoyiAvital** [comment]
OK, I have another suggestion after we solved this.

The `PyCall` and `Conda` installation are installing `Mini Conda` at the system level (Namely it is registered in registry and Start Menu items are added).

What's needed to be edited is the flags of the installation command at `Conda.jl`: https://github.com/JuliaPy/Conda.jl/blob/c745f2f2bb35f02bd4fc2f09e5c39c121daf6450/src/Conda.jl#L208.

The flags which should be added are: `/NoRegistry=1` and `--no-shortcuts`.

See https://github.com/conda/conda/issues/7507 and https://github.com/JuliaPy/Conda.jl/issues/147.
