### ISSUE TITLE
Could you please add a LICENSE?

### ISSUE THREAD

**Issue by efJerryYang** [heetbeet/juliawin#62]
Could you please add a license to this repo? I want to use the code but have copyright concerns. Thanks!

**Comment by heetbeet** [comment]
No problem, what would be the most relevant license for you that ensures maximum freedom? If you don't mind suggest a LICENSE.md file that I can add and I'll add it

**Comment by efJerryYang** [comment]
Thank you! MIT license is preferred, and I won't use it for commercial purposes, so any one of the GPL licenses will also be fine.
